"""Generate function discovery artifacts from the workflow catalogue.

The catalogue at ``vivainsights/discovery/workflows.yml`` is the single source of
truth. This script regenerates:

* ``docs/function-discovery.md`` - task-oriented guide for the documentation site
* ``docs/llms.txt`` - compact agent-readable index published at the site root

Run from the repository root::

    python tools/generate_discovery.py

CI regenerates the artifacts and fails if the committed files differ.
"""

import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
CATALOGUE_PATH = ROOT / "vivainsights" / "discovery" / "workflows.yml"
GUIDE_PATH = ROOT / "docs" / "function-discovery.md"
LLMS_PATH = ROOT / "docs" / "llms.txt"

GENERATED_NOTE = (
    "Generated by tools/generate_discovery.py from "
    "vivainsights/discovery/workflows.yml. Do not edit manually."
)


def load_catalogue():
    with CATALOGUE_PATH.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def format_columns(workflow):
    required = workflow["required_columns"]
    selected = workflow["selected_columns"]
    parts = []
    if required:
        parts.append("fixed: " + ", ".join(f"`{name}`" for name in required))
    if selected:
        parts.append("selected: " + ", ".join(f"`{name}`" for name in selected))
    return "; ".join(parts) if parts else "none"


def build_guide(catalogue):
    workflows = catalogue["workflows"]
    lines = [
        f"<!-- {GENERATED_NOTE} -->",
        "",
        "# Find the right function",
        "",
        "This guide maps analysis tasks to **vivainsights** functions so analysts and",
        "AI agents can use established package workflows instead of rebuilding Viva",
        "Insights aggregation and visualization logic.",
        "",
        "Person queries consistently use `PersonId` and `MetricDate`. Metric and",
        "organizational attribute names vary by query, product version, and language",
        "locale, so they are passed explicitly through arguments such as `metric` and",
        "`hrvar`.",
        "",
        "## Task index",
        "",
        "| Task | Function | Returns |",
        "| --- | --- | --- |",
    ]

    for workflow in workflows:
        return_types = workflow["return_types"]
        returns = (
            ", ".join(f"`{value}`" for value in return_types)
            if return_types
            else workflow["returns"]
        )
        lines.append(
            f"| {workflow['task']} | `{workflow['python_function']}()` | {returns} |"
        )

    lines.extend(["", "## Workflow details", ""])

    for workflow in workflows:
        lines.extend(
            [
                f"### {workflow['task']}",
                "",
                f"- **Function**: [`{workflow['python_function']}()`]({workflow['documentation']})",
                "- **Use when**: " + "; ".join(workflow["intents"]),
                f"- **Input**: {workflow['input_grain']}",
                f"- **Columns**: {format_columns(workflow)}",
                f"- **Returns**: {workflow['returns']}",
                f"- **Privacy**: {workflow['privacy']}",
                "- **Related**: "
                + ", ".join(f"`{name}()`" for name in workflow["related"]),
                f"- **R counterpart**: `{workflow['r_function']}()` ({workflow['parity']})",
                "",
                "```python",
                "import vivainsights as vi",
                "",
                workflow["example"],
                "```",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def build_llms(catalogue):
    workflows = catalogue["workflows"]
    lines = [
        "# vivainsights (Python)",
        "",
        "> Python package for analyzing and visualizing Microsoft Viva Insights data."
        " Use these established workflows instead of reimplementing Viva Insights"
        " aggregation, segmentation, or visualization logic.",
        "",
        f"<!-- {GENERATED_NOTE} -->",
        "",
        "Conventions:",
        "",
        "- Import as `import vivainsights as vi`.",
        "- Person queries always use `PersonId` and `MetricDate`.",
        "- Metric and organizational attribute names vary by query, product version,",
        "  and language locale; pass them explicitly via arguments such as `metric`",
        "  and `hrvar` instead of assuming English column names.",
        "- Output form is selected with `return_type`; the R package uses `return`",
        "  because `return` is a reserved keyword in Python.",
        "- Grouped functions expose `mingroup`; keep this privacy threshold unless the",
        "  user explicitly chooses another valid threshold.",
        "- The full workflow catalogue ships with the package at",
        "  `vivainsights/discovery/workflows.yml`.",
        "",
        "## Workflows",
        "",
    ]

    for workflow in workflows:
        return_types = workflow["return_types"]
        returns = (
            "return_type: " + ", ".join(return_types)
            if return_types
            else workflow["returns"]
        )
        lines.append(
            f"- [{workflow['task']}]({workflow['documentation']}): "
            f"`{workflow['python_function']}()`; "
            f"input: {workflow['input_grain']}; {returns}; "
            f"privacy: {workflow['privacy']}"
        )

    lines.extend(
        [
            "",
            "## Documentation",
            "",
            "- [Task guide](https://microsoft.github.io/vivainsights-py/function-discovery.html):"
            " choose a function for an analysis task.",
            "- [Function reference](https://microsoft.github.io/vivainsights-py/modules.html):"
            " full API documentation.",
            "- [Analyst guide](https://microsoft.github.io/vivainsights-py/analyst-guide.html):"
            " importing evolving and localized query schemas.",
            "- [R and Python parity](https://microsoft.github.io/vivainsights-py/r-python-parity.html):"
            " moving between the two packages.",
            f"- [R package]({catalogue['r']['documentation']}):"
            " the R counterpart of this package.",
        ]
    )

    return "\n".join(lines).rstrip() + "\n"


def main():
    catalogue = load_catalogue()
    GUIDE_PATH.write_text(build_guide(catalogue), encoding="utf-8", newline="\n")
    LLMS_PATH.write_text(build_llms(catalogue), encoding="utf-8", newline="\n")
    print(f"Wrote {GUIDE_PATH.relative_to(ROOT)}")
    print(f"Wrote {LLMS_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
